-- 1. Création de la table RESTAURANT (La table "Mère")
CREATE TABLE RESTAURANT (
    id_restaurant NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR2(100) NOT NULL,
    adresse VARCHAR2(255) NOT NULL,
    latitude NUMBER(10, 6) NOT NULL, 
    longitude NUMBER(10, 6) NOT NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (id_restaurant)
);

-- 2. Création de la table TABLE_RESTO (L'enfant de RESTAURANT)
CREATE TABLE TABLE_RESTO (
    id_table NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_restaurant NUMBER NOT NULL,
    numero_table VARCHAR2(50) NOT NULL, 
    capacite_max NUMBER NOT NULL,
    CONSTRAINT pk_table_resto PRIMARY KEY (id_table),
    CONSTRAINT fk_table_restaurant FOREIGN KEY (id_restaurant) REFERENCES RESTAURANT(id_restaurant) ON DELETE CASCADE
);

-- 3. Création de la table RESERVATION (L'enfant de TABLE_RESTO)
CREATE TABLE RESERVATION (
    id_reservation NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_table NUMBER NOT NULL,
    nom_client VARCHAR2(100) NOT NULL,
    prenom_client VARCHAR2(100),
    telephone VARCHAR2(20) NOT NULL,
    date_heure_reservation DATE NOT NULL,
    nb_convives NUMBER NOT NULL,
    est_midi VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (id_reservation),
    CONSTRAINT fk_resa_table FOREIGN KEY (id_table) REFERENCES TABLE_RESTO(id_table) ON DELETE CASCADE
);