# Configuration du proxy SAE
# Ce fichier doit être placé à côté du .jar au moment de l'exécution

# Port sur lequel le proxy HTTP écoute
proxy.port=8080

# Adresse et port du service RMI (back sur charlemagne)
rmi.host=charlemagne.iut-nancy-charlemagne.fr
rmi.port=1099
rmi.service=RestaurantService

# Proxy IUT pour les appels HTTP sortants vers les APIs externes
# Laisser vide si vous exécutez hors réseau IUT (chez vous)
iut.proxy.host=proxy.iut-nancy-charlemagne.fr
iut.proxy.port=3128
